services:
  toa-group-deploy-testing:
    build:
      context: .
      dockerfile: Dockerfile
    image: toa-group-deploy-testing:1.0.0
    container_name: toa-group-deploy-testing
    ports:
      - "3000:3000"
    networks:
      - network_services
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=1536"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: toa-group-deploy-testing-nginx
    ports:
      - "80:80"
    depends_on:
      toa-group-deploy-testing:
        condition: service_healthy
    networks:
      - network_services
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

    environment:
      TZ: Asia/Bangkok

networks:
  network_services:
    driver: bridge